[package]
name = "ptp-macro"
version = "0.1.0"
edition = "2024"
authors = [
    "Nikolaos Karaolidis <nick@karaolidis.com>",
]

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
byteorder = "1.5.0"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }
ptp-cursor = { path = "../ptp-cursor" }

[dev-dependencies]
num_enum = "0.7.6"
