[package]
name = "codegen"
version = "0.1.0"
edition = "2024"
description = "Build-time codegen from FML JSON to Rust for fujicli"
authors = [
    "Nikolaos Karaolidis <nick@karaolidis.com>",
]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
heck = "0.5.0"
prettyplease = "0.2.37"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syn = { version = "2.0", features = ["full"] }
